version: "3.9"

services:
  tg-talk:
    build: .
    container_name: tg-talk-bot
    restart: unless-stopped
    environment:
      TG_TOKEN: "${TG_TOKEN}"
      TG_BOT_DATA_DIR: "/data"
    volumes:
      - ./data:/data
    networks:
      - bot-net

networks:
  bot-net:
    driver: bridge
